# Generated by Django 4.0.1 on 2022-02-20 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('item_type', models.CharField(max_length=20)),
                ('geo_place_id', models.CharField(max_length=50)),
                ('maximum_price', models.IntegerField(null=True)),
                ('minimum_construction_year', models.IntegerField(null=True)),
                ('minimum_size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(max_length=1000)),
                ('count_total', models.IntegerField()),
                ('count_new', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('load_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.loadconfiguration')),
            ],
        ),
    ]
