# Generated by Django 4.0 on 2022-01-09 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saves', models.IntegerField()),
                ('visits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XeProperty',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_total', models.IntegerField()),
                ('price_sqm', models.IntegerField()),
                ('size_sqm', models.DecimalField(decimal_places=1, max_digits=10)),
                ('construction_year', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('bathrooms', models.CharField(max_length=100, null=True)),
                ('bedrooms', models.CharField(max_length=100, null=True)),
                ('condition', models.CharField(max_length=100, null=True)),
                ('furnished', models.BooleanField(null=True)),
                ('renovated', models.BooleanField(null=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('property_type', models.CharField(max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.geolocation')),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.pagemetrics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.owner')),
            ],
        ),
    ]
