# Generated by Django 4.0.1 on 2022-01-30 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('ref_id', models.CharField(max_length=100, null=True)),
                ('company_title', models.CharField(max_length=100, null=True)),
                ('active_ads', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('xe_id', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('visits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XeResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_total', models.IntegerField()),
                ('price_sqm', models.IntegerField()),
                ('size_sqm', models.DecimalField(decimal_places=1, max_digits=10)),
                ('construction_year', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('bathrooms', models.CharField(max_length=100, null=True)),
                ('bedrooms', models.CharField(max_length=100, null=True)),
                ('commercial', models.BooleanField(null=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('property_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xe_id', models.IntegerField()),
                ('first_parsed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_parsed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateField(null=True)),
                ('modified', models.DateField(null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.xeresidence')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.geolocation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.owner')),
            ],
        ),
    ]
