# Generated by Django 4.0.1 on 2022-03-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
    ]
